projeto/levelcheck/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static

# (. significa que importa views da mesma directoria)

app_name = 'levelcheck'
urlpatterns = [
    path('', views.login_form, name='login_form'),
    path('logout', views.logout, name='logout'),
    path('createacc', views.create_acc, name='create_acc'),
    path('index', views.index, name='index'),
    path('allgames', views.all_games, name='all_games'),
    path('allcharacters', views.all_characters, name='all_characters'),
    path('allreviews', views.all_reviews, name='all_reviews'),
    path('allusers', views.all_users, name='all_users'),
    path('creategame', views.create_game, name='create_game'),
    path('deletegame/<str:title>', views.delete_game, name='delete_game'),
    path('creategenre', views.create_genre, name='create_genre'),
    path('review/vote/<int:review_id>/<str:type>', views.review_feedback_vote, name='review_feedback_vote'),
    path('stats/<str:title>/<str:type>', views.user_games_stats, name='user_games_stats'),
    path('follow/<str:owner_id>', views.follower_followed, name='follower_followed'),
    path('favourite/<str:title>/<str:name>', views.user_characters_favourites, name='user_characters_favourites'),
    path('createcharacter', views.create_character, name='create_character'),
    path('createarticle', views.create_article, name='create_article'),
    path('deletecharacter/<str:title>/<str:name>', views.delete_character, name='delete_character'),
    path('createreview/<str:title>', views.create_review, name='create_review'),
    path('deletereview/<str:game_id>', views.delete_review, name='delete_review'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('editprofile/<int:id>', views.edit_profile, name='edit_profile'),
    path('<int:id>', views.user_detail, name='user_detail'),
    path('<str:title>', views.game_detail, name='game_detail'),
    path('<str:title>/<str:name>', views.character_detail, name='character_detail'),
    path('review/<str:username>/<int:id>', views.review_detail, name='review_detail'),
]

projeto/projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('levelcheck/', include('levelcheck.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto/levelcheck/models.py
import django.utils.timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Genre(models.Model):
    genre = models.CharField(max_length=50, primary_key=True)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=150)


class Game(models.Model):
    title = models.CharField(max_length=50, primary_key=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='games/')
    developer = models.CharField(max_length=50)
    publisher = models.CharField(max_length=50)
    release = models.DateField('Release Date')


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    review_title = models.CharField(max_length=50)
    text = models.CharField(max_length=300)
    rating = models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(0)])
    pub_date = models.DateTimeField('Posted', default=timezone.now)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user', 'game'], name='user_game_review')]


class ReviewFeedback(models.Model):
    FEEDBACK_OPTIONS = (('L', 'Like'), ('D', 'Dislike'))
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='feedback')
    type = models.CharField(max_length=1, choices=FEEDBACK_OPTIONS)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='feedback')

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user', 'review'], name='user_review_feedback')]


class Character(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    age = models.CharField(max_length=50)
    img = models.ImageField(upload_to='characters/')
    pub_date = models.DateTimeField('Posted', default=timezone.now)


class LevelUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=50, default="Prefer not")
    birthday = models.CharField(max_length=50)
    img_src = models.CharField(max_length=150)
    location = models.CharField(max_length=50, default="Earth")
    joined = models.DateField('Joined')
    bio = models.CharField(max_length=500, default="Your Bio!")

    def __str__(self):
        return self.user


class UserGames(models.Model):
    FEEDBACK_OPTIONS = (('P', 'Playing'), ('C', 'Completed'), ('H', 'Hold'), ('D', 'Dropped'), ('F', 'Plan-to-Play'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    type = models.CharField(max_length=1, choices=FEEDBACK_OPTIONS)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user', 'game'], name='user_game_stats')]


class UserCharacters(models.Model):
    FEEDBACK_OPTIONS = (('F', 'Favourite'), ('U', 'Unfavourite'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    type = models.CharField(max_length=1, choices=FEEDBACK_OPTIONS)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user', 'character', 'game'], name='user_character_favourites')]


class UserFollowers(models.Model):
    FEEDBACK_OPTIONS = (('F', 'Follow'), ('U', 'Unfollow'))
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    followed = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followed')
    type = models.CharField(max_length=1, choices=FEEDBACK_OPTIONS)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['follower', 'followed'], name='follower_followed')]


class Article(models.Model):
    title = models.CharField(max_length=75, primary_key=True)
    link = models.CharField(max_length=150)
    img = models.ImageField(upload_to='news/')
    pub_date = models.DateTimeField('Posted', default=timezone.now)

projeto/levelcheck/forms.py
from django import forms
from .models import Game, Genre, Character, Article

# Create your forms here.


class GameForm(forms.ModelForm):

    class Meta:
        model = Game
        fields = '__all__'


class GenreForm(forms.ModelForm):

    class Meta:
        model = Genre
        fields = '__all__'


class CharacterForm(forms.ModelForm):

    class Meta:
        model = Character
        exclude = ('pub_date',)


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ('pub_date',)

projeto/levelcheck/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import authenticate, login, logout as django_logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import GameForm, GenreForm, CharacterForm, ArticleForm
from itertools import chain


def login_form(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('index')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if not request.user.is_authenticated:
                login(request, user)
                return HttpResponseRedirect('index')
            else:
                return render(request, 'levelcheck/login_form.html', {'err_dupe': "You're already logged in."})
        else:
            return render(request, 'levelcheck/login_form.html', {'err_creds': "Username or Password are incorrect."})
        return
    else:
        return render(request, 'levelcheck/login_form.html')


@login_required(login_url='/levelcheck')
def logout(request):
    django_logout(request)
    return HttpResponseRedirect('/levelcheck')


def create_acc(request):
    if request.method == 'POST':
        username = request.POST['username']

        if User.objects.filter(username=username).exists():
            return render(request, 'levelcheck/create_acc.html', {'err_username': "Username in use."})
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            return render(request, 'levelcheck/create_acc.html', {'err_email': "E-mail in use."})

        email = request.POST['email']
        password = request.POST['password']
        birthday = request.POST['birthday']
        src = "/website/images/jiggly.jpg"
        joined = timezone.now()

        u = User.objects.create_user(username, email, password)
        u.save()
        level = LevelUser(user=u, birthday=birthday, img_src=src, joined=joined)
        level.save()
        return HttpResponseRedirect(reverse('levelcheck:login_form'))
    else:
        return render(request, 'levelcheck/create_acc.html')


@login_required(login_url='/levelcheck')
def index(request):
    games = Game.objects.all().order_by('-release')[:5]
    characters = Character.objects.all().order_by('-pub_date')[:5]
    reviews = Review.objects.all().order_by('-pub_date')[:5]
    news = Article.objects.all().order_by('-pub_date')[:10]
    return render(request, 'levelcheck/index.html', {'games': games, 'characters': characters, 'reviews': reviews, 'news': news})


@login_required(login_url='/levelcheck')
def profile(request, username):
    usergames = UserGames.objects.filter(user_id=request.user.id)
    games = Game.objects.none()
    games_list = list()

    for u in usergames:
        game = Game.objects.get(pk=u.game_id)
        games_list.append(game)

    query_games = list(chain(games, games_list))

    usercharacters = UserCharacters.objects.filter(user_id=request.user.id, type='F')
    characters = Character.objects.none()
    characters_list = list()

    for u in usercharacters:
        character = Character.objects.get(pk=u.character_id)
        characters_list.append(character)

    query_characters = list(chain(characters, characters_list))

    reviews = Review.objects.filter(user_id=request.user.id)

    playing = usergames.filter(type='P').count()
    completed = usergames.filter(type='C').count()
    hold = usergames.filter(type='H').count()
    dropped = usergames.filter(type='D').count()
    plan = usergames.filter(type='F').count()
    total = playing + completed + hold + dropped + plan

    userfollows = UserFollowers.objects.filter(follower_id=request.user.id)
    follows = LevelUser.objects.none()
    follows_list = list()

    for u in userfollows:
        follow = LevelUser.objects.get(user_id=u.followed_id)
        follows_list.append(follow)

    query_follows = list(chain(follows, follows_list))

    return render(request, 'levelcheck/profile.html', {'username': username, 'games': query_games, 'characters': query_characters, 'reviews': reviews, 'follows': query_follows, 'usergames': usergames, 'p': playing, 'c': completed, 'h': hold, 'd': dropped, 'f': plan, 't': total})


@login_required(login_url='/levelcheck')
def game_detail(request, title):
    game = get_object_or_404(Game, pk=title)
    reviews = Review.objects.filter(game_id=game.title)
    return render(request, 'levelcheck/game_detail.html', {'game': game, 'reviews': reviews})


@login_required(login_url='/levelcheck')
def character_detail(request, title, name):
    game = get_object_or_404(Game, pk=title)
    character = get_object_or_404(Character, name=name, game=game)
    character_relation = UserCharacters.objects.filter(user_id=request.user.id, character_id=character.id)
    if not character_relation:
        character_relation = 'E'
    return render(request, 'levelcheck/character_detail.html', {'game': game, 'character': character, 'relation': character_relation})


@login_required(login_url='/levelcheck')
def review_detail(request, username, id):
    review = get_object_or_404(Review, pk=id)
    likes = ReviewFeedback.objects.filter(type='L', review_id=id).count()
    dislikes = ReviewFeedback.objects.filter(type='D', review_id=id).count()
    return render(request, 'levelcheck/review_detail.html', {'review': review, 'likes': likes, 'dislikes': dislikes})


@login_required(login_url='/levelcheck')
def user_detail(request, id):
    profile_owner = get_object_or_404(LevelUser, pk=id)
    user_relation = UserFollowers.objects.filter(follower_id=request.user.id, followed_id=profile_owner.user.id)
    if not user_relation:
        user_relation = 'E'
    if request.user.id == profile_owner.user.id:
        url = reverse('levelcheck:profile', kwargs={'username': request.user.username})
        return HttpResponseRedirect(url)

    usergames = UserGames.objects.filter(user_id=profile_owner.user.id)
    games = Game.objects.none()
    games_list = list()

    for u in usergames:
        game = Game.objects.get(pk=u.game_id)
        games_list.append(game)

    query_games = list(chain(games, games_list))

    usercharacters = UserCharacters.objects.filter(user_id=profile_owner.user.id, type='F')
    characters = Character.objects.none()
    characters_list = list()

    for u in usercharacters:
        character = Character.objects.get(pk=u.character_id)
        characters_list.append(character)

    query_characters = list(chain(characters, characters_list))

    reviews = Review.objects.filter(user_id=profile_owner.user.id)

    playing = usergames.filter(type='P').count()
    completed = usergames.filter(type='C').count()
    hold = usergames.filter(type='H').count()
    dropped = usergames.filter(type='D').count()
    plan = usergames.filter(type='F').count()
    total = playing + completed + hold + dropped + plan

    userfollows = UserFollowers.objects.filter(follower_id=profile_owner.user.id)
    follows = LevelUser.objects.none()
    follows_list = list()

    for u in userfollows:
        follow = LevelUser.objects.get(user_id=u.followed_id)
        follows_list.append(follow)

    query_follows = list(chain(follows, follows_list))

    return render(request, 'levelcheck/user_detail.html', {'owner': profile_owner, 'relation': user_relation, 'games': query_games, 'characters': query_characters, 'reviews': reviews, 'follows': query_follows, 'usergames': usergames, 'p': playing, 'c': completed, 'h': hold, 'd': dropped, 'f': plan, 't': total})


@login_required(login_url='/levelcheck')
def edit_profile(request, id):
    if request.method == 'POST':
        leveluser = get_object_or_404(LevelUser, pk=id)
        username = leveluser.user.username

        if request.POST["gender"]:
            gender = request.POST["gender"]
        else:
            gender = leveluser.gender

        birthday = request.POST["birthday"]
        location = request.POST["location"]
        bio = request.POST["bio"]

        photo_filepath = request.FILES.get("photo", None)

        if photo_filepath is not None:
            src = request.FILES["photo"]
            fs = FileSystemStorage()
            filename = fs.save(src.name, src)
            uploaded_file_url_full = fs.url(filename)
            uploaded_file_url = uploaded_file_url_full.split("/", 3)[3]
            uploaded_file_url = "/" + uploaded_file_url
        else:
            uploaded_file_url = leveluser.img_src

        leveluser.gender = gender
        leveluser.birthday = birthday
        leveluser.location = location
        leveluser.bio = bio
        leveluser.img_src = uploaded_file_url

        leveluser.save(update_fields=["gender", "birthday", "location", "bio", "img_src"])
        url = reverse('levelcheck:profile', kwargs={'username': username})
        return HttpResponseRedirect(url)
    else:
        usergames = UserGames.objects.filter(user_id=request.user.id)
        games = Game.objects.none()
        games_list = list()

        for u in usergames:
            game = Game.objects.get(pk=u.game_id)
            games_list.append(game)

        query_games = list(chain(games, games_list))

        usercharacters = UserCharacters.objects.filter(user_id=request.user.id, type='F')
        characters = Character.objects.none()
        characters_list = list()

        for u in usercharacters:
            character = Character.objects.get(pk=u.character_id)
            characters_list.append(character)

        query_characters = list(chain(characters, characters_list))

        reviews = Review.objects.filter(user_id=request.user.id)

projeto/levelcheck/templates/levelcheck/all_games.html
{% extends "levelcheck/index.html" %}

{% block tab %}
    <title>Games</title>
{% endblock %}

{% block content %}
    <header style="height: 5%"><h1>GAMES</h1></header>
    <section style="height: 94.7%">
        <table>
            <tr>
                <th></th>
			    <th>Title</th>
			    <th>Genre</th>
			    <th>Developer</th>
                <th>Publisher</th>
                <th>Release Date</th>
                {% if request.user.is_superuser %}
                    <th></th>
                {% endif %}
            </tr>
            {% for g in games %}
            <tr style="text-align: center" data-href="{% url 'levelcheck:game_detail' g.title %}">
                <td style="width: 2.5%"><img class="table_image" src="{{ g.img.url }}"></td>
                <td style="width: 5%; font-weight: bold; font-size: 1.5em">{{ g.title }}</td>
                <td style="width: 5%">{{ g.genre_id }}</td>
                <td style="width: 5%">{{ g.developer }}</td>
                <td style="width: 5%">{{ g.publisher }}</td>
                <td style="width: 5%">{{ g.release }}</td>
                {% if request.user.is_superuser %}
                    <td style="width: 5%"><a style="padding: 3%" class="link_button" href="{% url 'levelcheck:delete_game' g.title %}">Delete</a></td>
                {% endif %}
            </tr>
            {% empty %}
                <tr style="text-align: center">
                    <td></td>
                    <td style="font-weight: bold; font-size: 1.5em">No games :(</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
        </table>
    </section>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const rows = document.querySelectorAll("tr[data-href]");

            rows.forEach(row => {
                row.addEventListener("click", () => {
                    window.location.href = row.dataset.href;
                });
            });
        });
    </script>
{% endblock %}

projeto/levelcheck/templates/levelcheck/character_detail.html
{% extends "levelcheck/profile.html" %}

{% block tab %}
    <title>{{character.name}}</title>
{% endblock %}

{% block character %}
    <img id="profile_pic" src="{{ character.img.url }}">
    <div style="font-size: 1em" id="profile_desc">
        <p><span>Game:</span>  {{game.title}}</p><br>
        <p><span>Name:</span>  {{character.name}}</p><br>
        <p><span>Age:</span>  {{character.age}}</p>
    </div>
{% endblock %}

{% block detail %}
    <section></section>
    <div style="margin: auto; width: 30%; text-align: center">
        {% if not request.user.is_superuser %}
            {% if relation.type == 'D' or relation == 'E' %}
            <a style="padding-right: 2%; padding-left: 2%; margin-right: 2%" class="link_button" href="{% url 'levelcheck:user_characters_favourites' game.title character.name %}">Favourite</a>
            {% else %}
            <a style="padding-right: 2%; padding-left: 2%; margin-left: 2%" class="link_button" href="{% url 'levelcheck:user_characters_favourites' game.title character.name %}">Unfavourite</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

projeto/levelcheck/templates/levelcheck/game_detail.html
{% extends "levelcheck/profile.html" %}

{% block tab %}
    <title>{{game.title}}</title>
{% endblock %}

{% block character %}
    <img id="profile_pic" src="{{ game.img.url }}">
    <div style="font-size: 1em" id="profile_desc">
        <p><span>Title:</span>  {{game.title}}</p><br>
        <p><span>Genre:</span>  {{game.genre_id}}</p><br>
        <p><span>Developer:</span>  {{game.developer}}</p><br>
        <p><span>Publisher:</span>  {{game.publisher}}</p><br>
        <p><span>Release Date:</span></p>
        <p>{{game.release}}</p><br>
        {% if not request.user.is_superuser %}
            <div class="dropdown">
            <button class="dropbtn">Set Status</button>
            <div class="dropdown-content">
                <a href="{% url 'levelcheck:user_games_stats' game.title "P" %}">Playing</a>
                <a href="{% url 'levelcheck:user_games_stats' game.title "C" %}">Completed</a>
                <a href="{% url 'levelcheck:user_games_stats' game.title "H" %}">On-Hold</a>
                <a href="{% url 'levelcheck:user_games_stats' game.title "D" %}">Dropped</a>
                <a href="{% url 'levelcheck:user_games_stats' game.title "F" %}">Plan to Play</a>
            </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block detail %}
    <header><h1>REVIEWS</h1></header>
    <section style="height: 83%">
        <table>
            <tr>
                <th>Title</th>
                <th>Reviewer</th>
                <th>Rating</th>
            </tr>
            {% for r in reviews %}
                <tr style="text-align: center" data-href="{% url 'levelcheck:review_detail' r.user.username r.id %}">
                    <td style="width: 5%; font-weight: bold; font-size: 1.5em">{{ r.review_title }}</td>
                    <td style="width: 5%">{{ r.user.username }}</td>
                    <td style="width: 5%">{{ r.rating }}</td>
                </tr>
            {% empty %}
                <tr style="text-align: center">
                    <td style="font-weight: bold; font-size: 1.5em">No reviews :(</td>
                    <td></td>
                    <td></td>
                </tr>
            {% endfor %}
        </table>
    </section>
    <div style="height: 7%" class="section_button">
        {% if not request.user.is_superuser %}
            <a style="width: 7.5%" class="link_button" href="{% url 'levelcheck:create_review' game.title%}">Add Review</a>
        {% endif %}
    </div>
{% endblock %}

projeto/levelcheck/templates/levelcheck/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block tab %}
    <title>Index</title>
    {% endblock %}
    {% load static %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/base.css' %}" />
    {% endblock %}
    <link rel="shortcut icon" type="image/png" href="{% static 'website/images/folder.png' %}"/>
</head>
<body>
<nav>
    <div style="display: flex; height: 98%">
        <a class="nav_link" style="width: 75px; padding-top: 3.5%" href="{% url 'levelcheck:index' %}">INDEX</a>
        <a class="nav_link" style="width: 85px; padding-top: 3.5%" href="{% url 'levelcheck:all_games' %}">GAMES</a>
        <a class="nav_link" style="width: 130px; padding-top: 3.5%" href="{% url 'levelcheck:all_characters' %}">CHARACTERS</a>
        <a class="nav_link" style="width: 100px; padding-top: 3.5%" href="{% url 'levelcheck:all_reviews' %}">REVIEWS</a>
        <a class="nav_link" style="width: 75px; padding-top: 3.5%" href="{% url 'levelcheck:all_users' %}">USERS</a>
    </div>
    {% if not request.user.is_superuser %}
        <h1 id="greeting">WELCOME {{request.user.username}}!</h1>
    {% endif %}
    {% if request.user.is_superuser %}
        <div style="display: flex; height: 95%">
            <a class="nav_link" style="width: 140px; padding-top: 2.4%" href="{% url 'levelcheck:create_game' %}">CREATE GAME</a>
            <a class="nav_link" style="width: 145px; padding-top: 2.4%" href="{% url 'levelcheck:create_genre' %}">CREATE GENRE</a>
            <a class="nav_link" style="width: 190px; padding-top: 2.4%" href="{% url 'levelcheck:create_character' %}">CREATE CHARACTER</a>
            <a class="nav_link" style="width: 140px; padding-top: 2.4%" href="{% url 'levelcheck:create_article' %}">CREATE NEWS</a>
            <a class="nav_link" style="width: 90px; padding-top: 2.4%" href="{% url 'levelcheck:logout' %}">LOGOUT</a>
        </div>
    {% else %}
        <div style="display: flex; height: 98%">
            <a class="nav_link" style="width: 90px; padding-top: 9%" href="{% url 'levelcheck:profile' user.username %}">PROFILE</a>
            <a class="nav_link" style="width: 90px; padding-top: 9%" href="{% url 'levelcheck:logout' %}">LOGOUT</a>
        </div>
    {% endif %}
</nav>

<div id="main">
    {% block content %}
    <div id="top_left">
        <header><h1>RECENT GAMES</h1></header>
        <section>
            <table>
                <tr>
                    <th></th>
                    <th>Title</th>
                </tr>
                {% for g in games %}
                <tr style="text-align: center" data-href="{% url 'levelcheck:game_detail' g.title%}">
                    <td style="width: 15%"><img class="table_image" src="{{ g.img.url }}"></td>
                    <td style="font-weight: bold; font-size: 1.5em">{{ g.title }}</td>
                </tr>
                {% empty %}
                    <tr style="text-align: center">
                        <td></td>
                        <td style="font-weight: bold; font-size: 1.5em">No games :(</td>
                    </tr>
                {% endfor %}
            </table>
	    </section>
        <div class="section_button">
            <a class="link_button" href="{% url 'levelcheck:all_games' %}">SEE ALL</a>
        </div>
    </div>

    <div id="top_right">
        <header><h1>RECENT CHARACTERS</h1></header>
        <section>
            <table>
                <tr>
                    <th></th>
                    <th>Name</th>
                </tr>
                {% for c in characters %}
                <tr style="text-align: center" data-href="{% url 'levelcheck:character_detail' c.game.title c.name%}">
                    <td style="width: 15%"><img class="table_image" src="{{ c.img.url }}"></td>
                    <td style="font-weight: bold; font-size: 1.5em">{{ c.name }}</td>
                </tr>
                {% empty %}
                    <tr style="text-align: center">
                        <td></td>
                        <td style="font-weight: bold; font-size: 1.5em">No characters :(</td>
                    </tr>
                {% endfor %}
            </table>
	    </section>
        <div class="section_button">
            <a class="link_button" href="{% url 'levelcheck:all_characters' %}">SEE ALL</a>
        </div>
    </div>

    <div id="bottom_left">
        <header><h1>RECENT REVIEWS</h1></header>
        <section>
            <table>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Game</th>
                    <th>Rating</th>
                </tr>
                {% for r in reviews %}
                <tr style="text-align: center" data-href="{% url 'levelcheck:review_detail' r.user.username r.id %}">
                    <td style="width: 1.5%"><img class="table_image" src="{{ r.game.img.url }}"></td>
                    <td style="width: 5%; font-weight: bold; font-size: 1.5em">{{ r.review_title }}</td>
                    <td style="width: 5%">{{ r.game.title }}</td>
                    <td style="width: 5%">{{ r.rating }}</td>
                </tr>
                {% empty %}
                    <tr style="text-align: center">
                        <td></td>
                        <td style="font-weight: bold; font-size: 1.5em">No reviews :(</td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endfor %}
            </table>
	    </section>
        <div class="section_button">
            <a class="link_button" href="{% url 'levelcheck:all_reviews' %}">SEE ALL</a>
        </div>
    </div>

    <div id="bottom_right">
        <header><h1>NEWS</h1></header>
        <section>
            <table>
                <tr>
                    <th></th>
                    <th>Title</th>
                </tr>
                {% for n in news %}
                <tr style="text-align: center" data-href="{{ n.link }}">
                    <td style="width: 1.5%"><img class="table_image" src="{{ n.img.url }}"></td>
                    <td style="width: 5%; font-weight: bold; font-size: 1.5em">{{ n.title }}</td>
                </tr>
                {% empty %}
                    <tr style="text-align: center">
                        <td></td>
                        <td style="font-weight: bold; font-size: 1.5em">No new news :(</td>
                    </tr>
                {% endfor %}
            </table>
	    </section>
    </div>
    {% endblock %}
</div>

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const rows = document.querySelectorAll("tr[data-href]");

            rows.forEach(row => {
                row.addEventListener("click", () => {
                    window.location.href = row.dataset.href;
                });
            });
        });
    </script>
</body>
</html>